package com.mafuyu404.taczaddon.compat.tacz;

public enum TaczFeature {
    BACKPACK_AMMO_QUERY,
    BACKPACK_AMMO_CONSUME,
    LIBERATED_REFIT,
    GUNSMITH_SESSION,
    GUNSMITH_SCREEN_ACCESS,
    GUNSMITH_EXTERNAL_SOURCE_VIEW,
    GUNSMITH_CRAFT_BRIDGE,
    GUNSMITH_BROWSE_MEMORY,
    FAST_SWAP,
    SHOOT_WHILE_RELOADING,
    SLIDE_SHOOT,
    HUD_AMMO,
    TOOLTIP_EXTENSION,
    CLIENT_ANIMATION,
    BETTER_MELEE,
    AIM_CAMERA,
    CRAWL_DISABLE,
    TACZ_SSR5_CROSSHAIR
}
